# configuration for transaction-service

server.port=8082

secret.token=transactionSecret
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.probes.enabled=true
